ros__parameters:

  frequency: 30
  sensor_timeout: 0.1

  # IMU sensor
  imu0: /imu_plugin/out
  imu0_config: [false, false, false, true, true, true, false, false, false]
  imu0_differential: false
  imu0_remove_gravitational_acceleration: true

  # LiDAR (laser scan data)
  laser0: /scan
  laser0_config: [true, true, false, false, false, false]
  laser0_differential: false

  # Sonar sensor
  range0: /sensor/gazebo_ros_range_sensor/out
  range0_config: [true, false, false]
  range0_differential: false

  two_d_mode: true
  transform_time_offset: 0.0
  transform_timeout: 0.0
  publish_tf: true
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom
