<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.65" />
    <xacro:property name="base_width" value="0.45" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.063" />
    <xacro:property name="wheel_length" value="0.05" />

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

   <link name="caster_wheel_link_1">
        <visual>
            <geometry>
                <sphere radius="0.031" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.031" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.2" />
            <inertia ixx="0.00007938" ixy="0.0" ixz="0.0" iyy="0.00007938" iyz="0.0" izz="0.00007938" />
        </inertial>
    </link>

    <link name="caster_wheel_link_2">
        <visual>
            <geometry>
                <sphere radius="0.031" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.031" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.2" />
            <inertia ixx="0.00007938" ixy="0.0" ixz="0.0" iyy="0.00007938" iyz="0.0" izz="0.00007938" />
        </inertial>
    </link>

    <link name="caster_wheel_link_3">
        <visual>
            <geometry>
                <sphere radius="0.031" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.031" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.2" />
            <inertia ixx="0.00007938" ixy="0.0" ixz="0.0" iyy="0.00007938" iyz="0.0" izz="0.00007938" />
        </inertial>
    </link>

    <link name="caster_wheel_link_4">
        <visual>
            <geometry>
                <sphere radius="0.031" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.031  " />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.2" />
            <inertia ixx="0.00007938" ixy="0.0" ixz="0.0" iyy="0.00007938" iyz="0.0" izz="0.00007938" />
        </inertial>
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="0 -0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="0 0.225 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_1_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link_1" />
        <origin xyz="-0.181 -0.15 -0.0315" rpy="0 0 0" />
    </joint>

    <joint name="base_caster_wheel_2_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link_2" />
        <origin xyz="-0.181 0.15 -0.0315" rpy="0 0 0" />
    </joint>
    
    <joint name="base_caster_wheel_3_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link_3" />
        <origin xyz="0.181 0.15 -0.0315" rpy="0 0 0" />
    </joint>

    <joint name="base_caster_wheel_4_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link_4" />
        <origin xyz="0.181 -0.15 -0.0315" rpy="0 0 0" />
    </joint>

</robot>
